### ISSUE TITLE
Support stub for output parameter?

### ISSUE THREAD

**Issue by bishophu** [eranpeer/FakeIt#21]
For historic reasons, lots of project have APIs that use output parameters extensively. So, it would be nice and save a lot of time  modifying existing code in order to mock it if there is direct support for this kind APIs.

**Comment by eranpeer** [comment]
The last few days I was trying to think about direct support for out parameters but I could not come up with an elegant idea. Meantime you can specify the value of an out pram by stubbing the method with a lambda replacement. For example:
```c++
        struct ApiInterface {
            virtual bool apiMethod(int a, int b, int& result) = 0;
        };

        Mock<ApiInterface> mock;
        When(Method(mock, apiMethod)).AlwaysDo([](int a, int b, int& result) {
            result = a + b;
            return true;
        });

        int result;
        ASSERT_TRUE(mock.get().apiMethod(1,2,result));
        ASSERT_EQUAL(3,result);
```
I will continue thinking about it, maybe something similar to argument matchers will do the work.
Any suggestion?

**Comment by DamnnnSure** [comment]
First, I have to say I'm not very familiar with Gmock. When I look at its support for output arguments, I wouldn't say the test code looks very readable, despite its flexibility. I hope your solution wouldn't compromise test code clarity, which is one of the biggest features of this project, right?
I guess using lambdas to do the dirty work would suffice for now.

**Comment by eranpeer** [comment]
I agree, gmock is a good example for what we DON'T want to do.
Here is a gmock example with out parameters:

EXPECT_CALL(testobject, testfunction(_,_, _))
            .WillOnce(testing::SetArgReferee<0>(value1))
            .WillOnce(testing::SetArgReferee<1>(value2))
            .WillOnce(Return(true));


The current fakeit alternative is:

When(Method(testobject, testfunction)).Do([](auto& arg1, auto& arg2, auto
arg3)
{
 arg1 = value1;
 arg2 = value2;
 return true;
});

As you said, my biggest effort is trying to create a simple & expressive
syntax.
How about?:

When(Method(testobject, testfunction).Using(SetValue(value1),
SetValue(value2), _)).Return(true);

It is a little confusing though it is very short.

What we have here is an "ArgumentAssigner" instead of an "ArgumentMatcher"
for the first 2 parameters. The third parameter is an "in" parameter and we
use a simple matcher for it.

???


On Fri, May 8, 2015 at 8:01 AM, Binshuo Hu <notifications@github.com> wrote:
>
> First, I have to say I'm not very familiar with Gmock. When I look at its
support for output arguments, I wouldn't say the test code looks very
readable, despite its flexibility. I hope your solution wouldn't compromise
test code clarity, which is one of the biggest features of this project,
right?
> I guess using lambdas to do the dirty work would suffice for now.
>
> —
> Reply to this email directly or view it on GitHub.




--
Eran
972-52-8387550

**Comment by DamnnnSure** [comment]
···
When(Method(testobject, testfunction).Using(SetValue(value1),
SetValue(value2), _)).Return(true);
···
The `Using` kinda get me lost. The `Using` part ought to work with matchers, since they are conditions declared by the `When`. But here setters rather than matchers are used, I simply coudn't comprehend the intention of this statement. Does this statement mean it will set the first two arguments and return `true` for only one time?

I suppose if the `SetValue` appears in the `Return` part, it would be more clear.

**Comment by eranpeer** [comment]
You're right,
I think I'll just skip it.
We'll stick to the lambda replacement for now.
Thanks.
