### ISSUE TITLE
Can not mock derived class

### ISSUE THREAD

**Issue by Confuset** [eranpeer/FakeIt#42]
hey.

iam pretty new to FakeIt but I stumbled across something that is confusing me. I can't mock simple inherited classes.

Take that code for example
```c++
class HandlerBase
{};

class TMessage {};

class Handler : public HandlerBase
{
public:
	void Handle(TMessage message)
	{
		HandleMessage(message);
	}

	virtual	void HandleMessage(TMessage m) {};
};

SCENARIO()
{
	fakeit::Mock<Handler> m;
}
```
I get that compiler error: "Can't mock a type with multiple inheritance"

Iam using vs2015, fakeit and CATCH to run that code…And forgot to much about c++ to look closer…

Any ideas on that issue?

**Comment by hartness** [comment]
I think the message is misleading, the issue seems to be that your base class has no virtual methods.  Add one and it works:

class HandlerBase
{
    virtual void f() {}
};

try mocking the base class alone and you get a more relevant message:

" Can only mock a polymorphic type"

Why this should be a problem when you might want to mock a derived class with virtual methods that has a base class that has no virtual methods is not clear to me. 

Is this a real world problem for you or just hypothetical? You might want to add a virtual destructor in your base class, this also fixes the problem.

**Comment by Confuset** [comment]
Thanks for pointing that out.
I know that i can only mock polymorphic types, but assumed having Handler polymorphic is sufficient.

A can easily add a virtual dtor to that class, thats not a problem. But the errormessage probably should be clearer. Something like "Can't mock object. Ensure Base is polymorphic". That would have pointed me in the correct direction.

And yes this is a real world problem for me. If you count my small project at home the real world :-)

**Comment by eranpeer** [comment]
Yep, the message is misleading. I've just pushed a fix.

**Comment by Confuset** [comment]
Thank you for the fix :)
