### ISSUE TITLE
Clear invocations on mock, without resetting

### ISSUE THREAD

**Issue by helmesjo** [eranpeer/FakeIt#83]
Title says it all: 

How do I clear the invocations on a mock, _without resetting it completely_?

**Simple example:**

```
TEST(Add_AlreadyHasItem_ListenerIsNotNotified)
{
    auto mock = Mock<MyListener>();
    Fake(Method(mock, OnChange));
    auto container = MyContainer(&mock.get());
    auto item = MyItem();
    container.add(item); // Add once
    
    mock.clearInvocations(); // <--- This is what I want
    // mock.reset(); // <---- This is NOT what I want, mock might have 10 already faked methods, don't wanna redo it... :)
    
    container.add(item); // Add twice

    Verify(Method(mock, OnChange)).Never();
}
```

Scimmed through your code but can't seem to find anything like this.

**Comment by helmesjo** [comment]
Note: I am aware of the many different ways to get around this (eg. in this case, instead of _Never()_, use _Once()_), but that is not a sustainable solution IMO.

**Comment by helmesjo** [comment]
@eranpeer Any thoughts?

**Comment by eranpeer** [comment]
I hope I will have time this week to add this functionality. It is a nice
enhancement and should be quite simple to implement.

On Apr 10, 2017 15:48, "Fred Helmesjö" <notifications@github.com> wrote:

@eranpeer <https://github.com/eranpeer> Any thoughts?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/eranpeer/FakeIt/issues/83#issuecomment-292939278>, or mute
the thread

**Comment by eranpeer** [comment]
More than week, but finally done.
I added a ClearInvocationHistory() method. It will clear the recorded invocations but keep the stubbing.
Hope it solves this issue.

**Comment by helmesjo** [comment]
Great! I've tried a lot of frameworks (mostly C#) and this feature is indeed very handy, especially in this case where one have to re-define the stubbs.

Thank you!
