### ISSUE TITLE
inline catch

### ISSUE THREAD

**Issue by dvirtz** [eranpeer/FakeIt#87]
First, grate library.

Can you tell me why is Catch framework inlined on the single header while other, like gtest, are not?
It causes collisions with the standalone Catch I use.

**Comment by eranpeer** [comment]
Oops, looks like a mistake.
Fixed it. Please try the latest commit.
Thanks,

**Comment by dvirtz** [comment]
Thanks. When do you plan to release it?

**Comment by eranpeer** [comment]
Did you try it? If yes I will create a release.

On Mar 29, 2017 21:20, "dvirtz" <notifications@github.com> wrote:

Thanks. When do you plan to release it?

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/eranpeer/FakeIt/issues/87#issuecomment-290179205>, or mute
the thread

**Comment by eranpeer** [comment]
The new single header for fakeit for catch is already on mater and can be
used.

**Comment by dvirtz** [comment]
I can't reproduce the original problem I had (something with Catch::Matcher) but my code is working well with the new version.
I now have to include catch.hpp before fakeit.hpp, however. Wouldn't it be better to include it from fakeit?

**Comment by eranpeer** [comment]
I think it is better to let the user define the include path. Not sure it
is right to assume catch is directly on the include path. What if the user
puts catch in a sub folder of a folder in the path and uses the line
"include somefolder/catch.hpp" in the tests code?
Not sure, what do you think?
