### ISSUE TITLE
({Unknown expression after the reported line})

### ISSUE THREAD

**Issue by jmcarter17** [eranpeer/FakeIt#89]
Hey Great Library,

One comment though, when I do a Verify call that fails, Catch reports ({Unknown expression after the reported line}) for the Test, but no interesting comment on which line caused the problem, and what that problem was.

I'm using latest Catch (v1.8.2) and FakeIt/single_header/catch/fakeit.hpp (Generated: 2017-03-29 07:39:05.028581). 

Here is the code:
```
TEST_CASE("Test FakeIt") {
    Mock<ICompressor> mockCompressor;
    auto& myComp = mockCompressor.get();

    When(Method(mockCompressor, getState)).Return(ICompressor::compState::idle);
    When(Method(mockCompressor, start)).AlwaysReturn();
    When(Method(mockCompressor, stop)).AlwaysReturn();

    CHECK(ICompressor::compState::idle == myComp.getState());

    myComp.start();
    myComp.stop();
    Verify(Method(mockCompressor, start)).AtLeastOnce();
    VerifyNoOtherInvocations(Method(mockCompressor, stop));
}
```

Is this because my setup is wrong or is this simply a feature not yet implemented.

Thanks

**Comment by eranpeer** [comment]
Hi,
The message should be more expressive. You're doing nothing wrong. I will
look into it this week.
Thanks,


On Apr 7, 2017 17:55, "Jean-Michel Carter" <notifications@github.com> wrote:

Hey Great Library,

One comment though, when I do a Verify call that fails, Catch reports
({Unknown expression after the reported line}) for the Test, but no
interesting comment on which line caused the problem, and what that problem
was.

I'm using latest Catch (v1.8.2) and FakeIt/single_header/catch/fakeit.hpp
(Generated: 2017-03-29 07:39:05.028581).

Here is the code:

TEST_CASE("Test FakeIt") {
    Mock<ICompressor> mockCompressor;
    auto& myComp = mockCompressor.get();

    When(Method(mockCompressor, getState)).Return(ICompressor::compState::idle);
    When(Method(mockCompressor, start)).AlwaysReturn();
    When(Method(mockCompressor, stop)).AlwaysReturn();

    CHECK(ICompressor::compState::idle == myComp.getState());

    myComp.start();
    myComp.stop();
    Verify(Method(mockCompressor, start)).AtLeastOnce();
    VerifyNoOtherInvocations(Method(mockCompressor, stop));
}

Is this because my setup is wrong or is this simply a feature not yet
implemented.

Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eranpeer/FakeIt/issues/89>, or mute the thread

**Comment by eranpeer** [comment]
It should be fixed now. You can use the source or the single_header Catch file. I fixed the Catch integration to work with the latest Catch version.
Please try it and update me if needed.
Thanks for raising this issue.

**Comment by jmcarter17** [comment]
Yes, much better now, 
thanks for the quick fix.
