### ISSUE TITLE
Is it possible to mock just a function?

### ISSUE THREAD

**Issue by brunohkbx** [eranpeer/FakeIt#91]
Lets say that I have the following function:

```
int add(x, y)
{
    return x + y;
}
```

Is it possible to mock the result?
All examples that I saw in examples was required an interface.

```
// Instantiate a mock object.
Mock<SomeInterface> mock;

// Setup mock behavior.
When(Method(mock,foo)).Return(1); // Method mock.foo will return 1 once.
```

**Comment by eranpeer** [comment]
No,
Fakeit manipulates the virtual table. It can only​ mock a class.


On Apr 26, 2017 5:24 AM, "Bruno Castro" <notifications@github.com> wrote:

Lets say that I have the following function:

int add(x, y)
{
    return x + y;
}

Is it possible to mock the result?
All examples that I saw in examples was required an interface.

// Instantiate a mock object.
Mock<SomeInterface> mock;

// Setup mock behavior.
When(Method(mock,foo)).Return(1); // Method mock.foo will return 1 once.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/eranpeer/FakeIt/issues/91>, or mute the thread

**Comment by dolfandringa** [comment]
There is a way to make it work though by creating a class that you can mock/stub, and make fake versions of the functions to test that call that class. Here is a sample. please comment if I have overlooked something.

 ```

struct MockFunctions {
    virtual int add(int x, int y) = 0;
    virtual int sub(int x, int y) = 0;
}

Mock<MockFunctions> FakeFunctions;
MockFunctions* pFakeFunctions;

MockFunctions* getFakeFunctionsInstance() {
    //Get a singleton FakeFunctions
    if(!pFakeFunctions) {
        pFakeFunctions = &FakeFunctions.get();
    }
    return pFakeFunctions;
}

int add(int x, int y) {
    return getFakeFunctionsInstance()->add(x, y);
}

int sub(int x, int y) {
    return getFakeFunctionsInstance()->sub(x, y);
}

When(Method(FakeFunctions, add)).AlwaysReturn(10);
TEST_ASSERT_EQUAL(add(5, 6), 10));
```
